#include "s21_string.h"

#ifdef __APPLE__
static const char* mac_error_messages[] = {
   "Operation not permitted",
   "No such file or directory",
   "No such process",
   "Interrupted system call",
   "Input/output error",
   "Device not configured",
   "Argument list too long",
   "Exec format error",
   "Bad file descriptor",
   "No child processes",
   "Resource deadlock avoided",
   "Cannot allocate memory",
   "Permission denied",
   "Bad address",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Block device required",
#endif
   "Device / Resource busy",
   "File exists",
   "Cross-device link",
   "Operation not supported by device",
   "Not a directory",
   "Is a directory",
   "Invalid argument",
   "Too many open files in system",
   "Too many open files",
   "Inappropriate ioctl for device",
   "Text file busy",
   "File too large",
   "No space left on device",
   "Illegal seek",
   "Read-only file system",
   "Too many links",
   "Broken pipe",
   "Numerical argument out of domain",
   "Result too large",
   "Resource temporarily unavailable",
   "Operation would block",
   "Operation now in progress",
   "Operation already in progress",
   "Socket operation on non-socket",
   "Destination address required",
   "Message too long",
   "Protocol wrong type for socket",
   "Protocol not available",
   "Protocol not supported",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Socket type not supported",
#endif
   "Operation not supported",
#if !__DARWIN_UNIX03 && !defined(KERNEL)
   "Operation not supported on socket",
#endif
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Protocol family not supported",
#endif
   "Address family not supported by protocol family",
   "Address already in use",
   "Can't assign requested address",
   "Network is down",
   "Network is unreachable",
   "Network dropped connection on reset",
   "Software caused connection abort",
   "Connection reset by peer",
   "No buffer space available",
   "Socket is already connected",
   "Socket is not connected",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Can't send after socket shutdown",
   "Too many references: can't splice",
#endif
   "Operation timed out",
   "Connection refused",
   "Too many levels of symbolic links",
   "File name too long",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Host is down",
#endif
   "No route to host",
   "Directory not empty",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Too many processes",
   "Too many users",
#endif
   "Disc quota exceeded",
   "Stale NFS file handle",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Too many levels of remote in path",
   "RPC struct is bad",
   "RPC version wrong",
   "RPC prog. not avail",
   "Program version wrong",
   "Bad procedure for program",
#endif
   "No locks available",
   "Function not implemented",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Inappropriate file type or format",
   "Authentication error",
   "Need authenticator",
   "Device power is off",
   "Device error, e.g. paper out",
#endif
   "Value too large to be stored in data type",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Bad executable",
   "Bad CPU type in executable",
   "Shared library version mismatch",
   "Malformed Macho file",
#endif
   "Operation canceled",
   "Identifier removed",
   "No message of desired type",
   "Illegal byte sequence",
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Attribute not found",
#endif
   "Bad message",
   "Reserved",
   "No message available on STREAM",
   "Reserved",
   "No STREAM resources",
   "Not a STREAM",
   "Protocol error",
   "STREAM ioctl timeout",
#if __DARWIN_UNIX03 || defined(KERNEL)
   "Operation not supported on socket",
#endif
   "No such policy registered",
#if __DARWIN_C_LEVEL >= 200809L
   "State not recoverable",
   "Previous owner died",
#endif
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
   "Interface output queue is full",
   "Must be equal largest errno"
#endif
};

#elif defined(__linux__)
static const char* linux_error_messages[] = {
   "Operation not permitted",
   "No such file or directory",
   "No such process",
   "Interrupted system call",
   "Input/output error",
   "No such device or address",
   "Argument list too long",
   "Exec format error",
   "Bad file descriptor",
   "No child processes",
   "Resource deadlock avoided",
   "Cannot allocate memory",
   "Permission denied",
   "Bad address",
   "Block device required",
   "Device / Resource busy",
   "File exists",
   "Cross-device link",
   "Operation not supported by device",
   "Not a directory",
   "Is a directory",
   "Invalid argument",
   "Too many open files in system",
   "Too many open files",
   "Inappropriate ioctl for device",
   "Text file busy",
   "File too large",
   "No space left on device",
   "Illegal seek",
   "Read-only file system",
   "Too many links",
   "Broken pipe",
   "Math argument out of domain of func",
   "Math result not representable",
   "Resource deadlock would occur",
   "File name too long",
   "No record locks available",
   "Function not implemented",
   "Directory not empty",
   "Too many symbolic links encountered",
   "Operation would block",
   "No message of desired type",
   "Identifier removed",
   "Channel number out of range",
   "Level 2 not synchronized",
   "Level 3 halted",
   "Level 3 reset",
   "Link number out of range",
   "Protocol driver not attached",
   "No CSI structure available",
   "Level 2 halted",
   "Invalid exchange",
   "Invalid request descriptor",
   "Exchange full",
   "No anode",
   "Invalid request code",
   "Invalid slot",
   "Resource deadlock avoided",
   "Bad font file format",
   "Device not a stream",
   "No data available",
   "Timer expired",
   "Out of streams resources",
   "Machine is not on the network",
   "Package not installed",
   "The object is remote",
   "Advertise error",
   "Srmount error",
   "Communication error on send",
   "Protocol error",
   "Multihop attempted",
   "RFS specific error",
   "Bad message",
   "Value too large for defined data type",
   "Name not unique on network",
   "File descriptor in bad state",
   "Remote address changed",
   "Can not access a needed shared library",
   "Accessing a corrupted shared library",
   ".lib section in a.out corrupted",
   "Attempting to link in too many shared libraries",
   "Cannot exec a shared library directly",
   "Invalid or incomplete multibyte or wide character",
   "Interrupted system call should be restarted",
   "Streams pipe error",
   "Too many users",
   "Socket operation on non-socket",
   "Destination address required",
   "Message too long",
   "Protocol wrong type for socket",
   "Protocol not available",
   "Protocol not supported",
   "Socket type not supported",
   "Operation not supported",
   "Protocol family not supported",
   "Address family not supported by protocol",
   "Address already in use",
   "Can't assign requested address",
   "Network is down",
   "Network is unreachable",
   "Network dropped connection on reset",
   "Software caused connection abort",
   "Connection reset by peer",
   "No buffer space available",
   "Socket is already connected",
   "Socket is not connected",
   "Can't send after socket shutdown",
   "Too many references: can't splice",
   "Operation timed out",
   "Connection refused",
   "Host is down",
   "No route to host",
   "Directory not empty",
   "Too many processes",
   "Too many users",
   "Disc quota exceeded",
   "Stale NFS file handle",
   "Too many levels of remote in path",
   "RPC struct is bad",
   "RPC version wrong",
   "RPC prog. not avail",
   "Program version wrong",
   "Bad procedure for program",
   "No locks available",
   "Function not implemented",
   "Inappropriate file type or format",
   "Authentication error",
   "Need authenticator",
   "Device power is off",
   "Device error, e.g. paper out",
   "Value too large to be stored in data type",
   "Bad executable",
   "Bad CPU type in executable",
   "Shared library version mismatch",
   "Malformed Macho file",
   "Operation canceled",
   "Identifier removed",
   "No message of desired type",
   "Illegal byte sequence",
   "Attribute not found",
   "Bad message",
   "No message available on STREAM",
   "No STREAM resources",
   "Not a STREAM",
   "Protocol error",
   "STREAM ioctl timeout",
   "Operation not supported on socket",
   "No such policy registered",
   "State not recoverable",
   "Previous owner died",
   "Interface output queue is full",
   "Must be equal largest errno"
};

#endif

char* s21_strerror(int errnum) {
    char** error_messages = S21_NULL;

   #ifdef __APPLE__
   error_messages = (char**)mac_error_messages;
   #elif defined(__linux__)
   error_messages = (char**)linux_error_messages;
   #endif
   if (errnum >= 0 && errnum < sizeof(error_messages) / sizeof(error_messages[0])) {
       return (char*)error_messages[errnum];
   }
   return (char*)"Unknown error";
}